import = [ "~/.config/alacritty/themes/github_light.toml" ]

[mouse]
hide_when_typing = true
[scrolling]
history = 5000
[window]
decorations = "buttonless"
dynamic_padding = false
title = "Miku"
option_as_alt = "Both"
[window.class]
general = "Alacritty"
instance = "Alacritty"
[window.padding]
x = 0
y = 0
[window.position]
x = 650
y = 250
[env]
TERM = "xterm-256color"

[font]
size = 16
[font.normal]
family = "Iosevka Nerd Font Mono"
[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "\n"
key = "Return"
mods = "Control"
