import = [ "~/.config/alacritty/themes/github_dark.toml" ]

[env]
TERM = "xterm-256color"
[window]
decorations = "buttonless"
dynamic_padding = true
option_as_alt = "Both"
padding = { x = 0, y = 0 }
position={ x = 650 ,y = 250}
[font]
size = 16
normal = { family = "Iosevka Nerd Font Mono",style = "Regular"}
offset={ x = 0, y = 0}


