#!/usr/bin/env bash
CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
set -e


# NOTE: user
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # Color end

RIME_PATH="$HOME/Library/Rime"
RIME_URL="https://github.com/iDvel/rime-ice"

# check Rime dir
if [ -e "$RIME_PATH" ]; then
        printf  "${GREEN}File '$RIME_PATH' exists.${NC}\n"

        # Git dir
        if [ -d "$RIME_PATH/.git" ]; then
                printf "${GREEN}Updating...${NC}\n"
                cd "$RIME_PATH" || exit
                git pull
        else
                printf "${RED}'$RIME_PATH' is not a Git repository. Backing up and cloning...${NC}\n"
                mv "$RIME_PATH" "$HOME/Rime.bak"
                git clone "$RIME_URL" "$RIME_PATH"
        fi
else
        printf "${RED}'$RIME_PATH' does not exist. Cloning repository...${NC}\n"
        git clone "$RIME_URL" "$RIME_PATH"
fi


#NOTE: dotbot
cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
