command_timeout = 9999

[character] 
    success_symbol = "[󰅂](bold green)" 
    error_symbol = "[󰅂](bold red)"
     #  "[» ≡ ❯ 󰅂 󰁕  ➜  ]"  [≡](bold green)[❯](bold magenta)
[c]
    # disabled=true
    commands=[[ 'clang', '--version' ] ]

