[ -f "$HOME/.profile" ] && . "$HOME/.profile" 
[ "$(uname)" = "Darwin" -a -f "$HOME/.bashrc" ] && . "$HOME/.bashrc"  
[ "$XDG_SESSION_TYPE" = "x11" -a -f "$HOME/.xinitrc" ] && . "$HOME/.xinitrc"

[ -n "$SSH_TTY" ] && command -v fish >/dev/null 2>&1  && exec fish
