bind 'set bell-style none'
set -o emacs
shopt -s autocd
#don't show login last login info
[ ! -f "$HOME/.hushlogin" ] && touch "$HOME/.hushlogin" 

alias  v="nvim"

if [ -n "$DISPLAY" ] || [ -n "$TERM_PROGRAM" ] ;then
        exec fish
fi
