local api, opt, g = vim.api, vim.opt, vim.g
local M = {}

local cs = {
        fg = "#c8c8c8",
        bg = "#1e1e1e",
        alt_fg = "#c8c8c8",
        alt_bg = "#181818",
        cursorline = "#222222",
        blue_1 = "#569cd6",
        blue_2 = "#9CDCFE",
        blue_3 = "#4FC1FF",
        green_1 = "#6A9955",
        green_2 = "#b5cea8",
        red = "#d16969",
        cyan = "#4EC9B0",
        orange = "#CE9178",
        yellow = "#DCDCAA",
        dark_yellow = "#d7ba7d",
        purple = "#C586C0",
        light_gray = "#808080",
        dark_gray = "#6e7681",

        border = "#2d2d2d",
        visual = "#264f78",
        select = "#03395e",
        match_bg = "#194765",
        match = "#29a9ff",
        indent = "#3f3f3f",
        reference = "#323232",
        indent_active = "#636363",
        folder = "#c8c8c8",
        hint = "#4bc1fe",
        info = "#FFCC66",
        warn = "#ff8800",
        error = "#F44747",
        other = "#7c3aed",

        hint_bg = "#232e34",
        info_bg = "#342f25",
        warn_bg = "#34291b",
        error_bg = "#332222",

        gitsigns_add = "#2da042",
        gitsigns_change = "#0077d2",
        gitsigns_delete = "#f85249",
        git_tree_add = "#6dbd89",
        git_tree_change = "#e6c38f",
        git_tree_delete = "#f88372",
        statusline_bg = "#181818",
        ui_blue = "#0078d4",
        ui_orange = "#e29627",
        ui_white = "#ffffff",
        ui_purple = "#a779ca",
        ui_yellow = "#ffcc77",
        ui_green = "#14C50B",
}

local c = {
        fg             = "#D4D4D4",
        bg             = "#1E1E1E",
        dark           = "#252525",
        accent         = "#BBBBBB",
        popup_back     = "#2D2D30",
        gray           = "#808080",
        dark_gray      = "#3e3e3e",
        context        = "#606060",
        light_gray     = "#c8c9c1",
        black          = "#000000",
        blue           = "#9CDCFE",
        light_blue     = "#9CDCFE",
        green          = "#6A9955",
        red            = "#F44747",
        light_red      = "#D16969",
        orange         = "#CE9178",
        yellow         = "#DCDCAA",
        yellow_orange  = "#D7BA7D",
        purple         = "#C586C0",
        cursor_fg      = "#515052",
        cursor_bg      = "#AEAFAD",
        error_red      = "#F44747",
        warning_orange = "#ff8800",
        info_yellow    = "#FFCC66",
        hint_blue      = "#4FC1FF",

        diff_add       = "#10B981",
        diff_change    = "#FFFF00",
        diff_delete    = "#FF0000",
        diff_text      = "#FF0033",
        indent_line    = "#424948",
        vi_blue        = "#264F78",
}

local theme = {

        Boolean                  = { fg = c.yellow },
        Character                = { fg = c.green },
        ColorColumn              = { bg = c.dark },
        Comment                  = { fg = c.gray, },
        Conceal                  = { fg = c.accent, bg = c.bg },
        Conditional              = { fg = c.light_blue },
        Constant                 = { fg = c.yellow },
        Cursor                   = { fg = c.cursor_fg, bg = c.cursor_bg },
        CursorColumn             = { bg = c.dark },
        CursorIM                 = { fg = c.cursor_fg, bg = c.cursor_bg },
        CursorLine               = { bg = c.dark },
        CursorLineNr             = { fg = c.light_gray, },
        Debug                    = { fg = c.red },
        Define                   = { fg = c.purple },
        Delimiter                = { fg = c.fg },
        DiffAdd                  = { fg = c.diff_add, bg = c.dark },
        DiffAdded                = { fg = c.diff_add },
        DiffChange               = { bg = c.dark, fg = c.diff_change, },
        DiffDelete               = { fg = c.diff_delete, bg = c.dark },
        DiffRemoved              = { fg = c.diff_text },
        DiffText                 = { bg = c.dark, fg = c.diff_text },
        DiffFile                 = { fg = c.fg },
        DiffIndexLine            = { fg = c.indent_line },
        Directory                = { fg = c.light_blue },
        EndOfBuffer              = { fg = c.bg },
        Error                    = { fg = c.error_red, bg = c.bg, },
        ErrorMsg                 = { fg = c.error_red, bg = c.bg, },
        Exception                = { fg = c.purple },
        Float                    = { fg = c.yellow },
        FloatBorder              = { fg = c.gray, bg = c.dark },
        FoldColumn               = { fg = c.accent, bg = c.dark },
        Folded                   = { fg = c.accent, bg = c.dark },
        Function                 = { fg = c.purple },
        Identifier               = { fg = c.fg },
        Ignore                   = { fg = c.fg, bg = c.bg, },
        Search                   = { fg = c.black, bg = c.light_blue },
        IncSearch                = { fg = c.black, bg = c.red },
        CurSearch                = { link = 'IncSearch' },
        Include                  = { fg = c.purple },
        Keyword                  = { fg = c.purple },
        Label                    = { fg = c.light_blue },
        LineNr                   = { fg = c.context },
        Macro                    = { fg = c.purple },
        MatchParen               = { fg = c.red, },
        MatchParenCur            = { underline = true },
        MatchWord                = { underline = true },
        MatchWordCur             = { underline = true },
        ModeMsg                  = { fg = c.fg, bg = c.bg },
        MoreMsg                  = { fg = c.yellow },
        MsgArea                  = { fg = c.fg, bg = c.bg },
        MsgSeparator             = { fg = c.fg, bg = c.bg },
        NonText                  = { fg = c.context },
        Normal                   = { fg = c.fg, bg = c.bg },
        NormalFloat              = { bg = c.dark },
        NormalNC                 = { fg = c.fg, bg = c.bg },
        Number                   = { fg = c.yellow },
        Operator                 = { fg = c.purple },
        Pmenu                    = { fg = c.light_gray, bg = c.popup_back },
        PmenuSbar                = { bg = c.dark },
        PmenuSel                 = { fg = c.dark, bg = c.light_blue },
        PmenuThumb               = { bg = c.gray },
        PreCondit                = { fg = c.purple },
        PreProc                  = { fg = c.purple },
        Question                 = { fg = c.yellow },
        QuickFixLine             = { bg = c.dark_gray },
        Repeat                   = { fg = c.light_blue },
        SignColumn               = { bg = c.bg },
        Special                  = { fg = c.purple },
        SpecialChar              = { fg = c.fg },
        SpecialComment           = { fg = c.gray },
        SpecialKey               = { fg = c.light_blue, },
        --
        Statement                = { fg = c.purple },
        StatusLine               = { fg = c.dark, bg = "#212121" },
        StatusLineNC             = { fg = c.dark },
        StatusLineSeparator      = { fg = c.dark },
        StatusLineTerm           = { fg = c.dark },
        StatusLineTermNC         = { fg = c.dark },
        StorageClass             = { fg = c.fg },
        String                   = { fg = c.yellow },
        Structure                = { fg = c.purple },
        Substitute               = { fg = c.light_gray, bg = c.orange },
        TabLine                  = { fg = c.light_gray, bg = c.dark },
        TabLineFill              = { fg = c.fg, bg = c.dark },
        TabLineSel               = { fg = c.fg, bg = c.dark },
        Tag                      = { fg = c.light_blue },
        TermCursor               = { fg = c.cursor_fg, bg = c.cursor_bg },
        TermCursorNC             = { fg = c.cursor_fg, bg = c.cursor_bg },
        Title                    = { fg = c.light_blue, },
        Todo                     = { fg = c.red, bg = c.bg, bold = true },
        Type                     = { fg = c.light_blue }, --bold = false
        Typedef                  = { fg = c.purple },
        Variable                 = { fg = c.fg },
        VertSplit                = { fg = c.gray, },
        Visual                   = { bg = c.vi_blue },
        VisualNOS                = { bg = c.dark },
        WarningMsg               = { fg = c.yellow, bg = c.bg },
        Whitespace               = { fg = c.indent_line },
        WildMenu                 = { fg = c.dark, bg = c.light_blue },
        lCursor                  = { fg = c.cursor_fg, bg = c.cursor_bg },

        --NOTE:PLUGIN
        -- Cmp
        CmpDocumentation         = { fg = c.fg, bg = c.none },
        CmpDocumentationBorder   = { fg = c.gray, bg = c.none },
        CmpItemAbbr              = { fg = c.fg, bg = c.none },
        CmpItemAbbrDeprecated    = { fg = c.gray, bg = c.none },
        CmpItemAbbrMatch         = { fg = c.fg, bg = c.none },
        CmpItemAbbrMatchFuzzy    = { fg = c.fg, bg = c.none },
        CmpItemKind              = { fg = c.light_blue, bg = c.none },
        CmpItemMenu              = { fg = c.light_gray, bg = c.none },
        DashboardHeader          = { fg = c.light_blue },
        -- Lsp
        DiagnosticFloatingError  = { fg = c.error_red },
        DiagnosticFloatingHint   = { fg = c.hint_blue },
        DiagnosticFloatingInfo   = { fg = c.info_yellow },
        DiagnosticFloatingWarn   = { fg = c.warning_orange },
        DiagnosticSignError      = { fg = c.error_red },
        DiagnosticSignHint       = { fg = c.hint_blue },
        DiagnosticSignInfo       = { fg = c.info_yellow },
        DiagnosticSignWarn       = { fg = c.warning_orange },
        DiagnosticUnderlineError = { underline = true },
        DiagnosticUnderlineHint  = { underline = true },
        DiagnosticUnderlineInfo  = { underline = true },
        DiagnosticUnderlineWarn  = { underline = true },
        -- Telescope
        TelescopeBorder          = { fg = c.fg, bg = c.bg },
        TelescopeMatching        = { fg = c.orange, },
        TelescopePromptPrefix    = { fg = c.purple },
        TelescopeSelection       = { fg = c.purple },
        -- Flash
        FlashLabel               = { fg = "#000000", bg = c.purple },

}


M.setup = function()
        api.nvim_command('hi clear')
        opt.termguicolors = true
        opt.background = 'dark'
        g.colors_name = 'darkplus'

        for group, conf in pairs(theme) do
                api.nvim_set_hl(0, group, conf)
        end
end

return M
